name: "{{project_name}}"
description: "Project {{project_name}}"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Remote Data & Connectivity
  dio: ^5.8.0+1

  # UI Package
  flutter_spinkit: ^5.2.1
  icons_plus: ^5.0.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  calendar_date_picker2: ^2.0.0
  pull_to_refresh: ^2.0.0
  dropdown_textfield: ^1.2.0
  shimmer: ^3.0.0
  toastification: ^3.0.2

  # Internationalization & Localization
  intl: ^0.19.0

  # Functional Programming
  dartz: ^0.10.1

  # Dependencies Injector
  get_it: ^8.0.3

  # Route
  get: ^4.7.2

  # Value Comparator
  equatable: ^2.0.7

  # Debugging Dio
  pretty_dio_logger: ^1.4.0
  flutter_smart_dialog: ^4.9.8+7

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Local Storage
  hive_flutter: ^1.1.0

  # Encrypt
  crypto: ^3.0.6
  encrypt: ^5.0.3

  # Permission Handler
  permission_handler: ^12.0.0+1

  # Specify the equality of elements and collections.
  collection: ^1.19.1

  # Env Secret Variable
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - .env

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/ic_launcher.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 29 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  # image_path_ios: "assets/icon/ic_launcher.png"
  remove_alpha_channel_ios: false
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/ic_launcher.png"
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true
